# Generated by Django 2.1.2 on 2019-03-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_autttt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autttt',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
