# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-20 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181220_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='isAcitve',
            new_name='isActive',
        ),
    ]
